# MagnoFallas - A Python-based method for annihilating magnons
# Copyright (C) 2025-2026  Andrei Shumilin
#
# e-mail: andrei.shumilin@uv.es, hegnyshu@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.



r"""
Not perfectly tested - interface with MuMax3
"""


#########################

import numpy as np
import matplotlib.pyplot as plt
import copy


import MagnoFallas as mfal
from MagnoFallas.Utils import util2 as ut2
from MagnoFallas.Utils import MicroMagnetics as micro

from .constants import *

##########################

__all__ = ['Header','SquareGeometry']


def Header():
    r"""
    Writes the header for MuMax3 files
    """
    Lines = []
    Lines.append('/// Simulation of a single skyrmion \n')
    Lines.append('/// This file is automatically generated by the MagnoFallas code, developed by Andrei Shumilin\n')
    Lines.append('/// https://github.com/AndreiShumilin/MagnoFallas \n\n')
    Lines.append('\n\n\n')
    return Lines

def SquareGeometry(Lx=1000, Ly=1000, Nx=100, Ny=100, cz_nm = 1):
    r"""
    Sets the geometry of Lx x Ly rectangle (in Angstr)
    with Nx x Ny grid
    cz_nm --- effective thickness 
    """
    Lines = []
    Lines.append('/// ---->  Geometry Block <------------: \n')
    cx = (Lx/Nx)*1e-10
    cy = (Ly/Ny)*1e-10
    cz = cz_nm * 1e-9
    Lines.append(f'gridNx := {Nx} \n')
    Lines.append(f'gridNy := {Ny} \n')
    Lines.append(f'cx := {cx:.2e} \n')
    Lines.append(f'cy := {cy:.2e} \n')
    Lines.append(f'cz := {cz:.2e} \n')
    
    Lines.append('setgridsize(gridNx, gridNy, 1) \n')
    Lines.append('setcellsize(cx, cy, cz) \n')
    Lines.append('/// ---->  end of geometry <------------: \n')
    Lines.append('\n\n\n')
    return Lines
